// Auto-generated from "Industry and vertical tables.csv". See scripts/regenerate-taxonomy.js.
// Industry/Vertical taxonomy used across the CRM. Hard-coded on purpose:
// we do not expose a UI to edit these and the enrichment prompt references them.

export const INDUSTRIES = Object.freeze([
  "Accommodation and Food Services",
  "Administrative and Support and Waste Management and Remediation Services",
  "Agriculture, Forestry, Fishing and Hunting",
  "Arts, Entertainment, and Recreation",
  "Construction",
  "Educational Services",
  "Finance and Insurance",
  "Health Care and Social Assistance",
  "Information",
  "Management of Companies and Enterprises",
  "Manufacturing",
  "Mining, Quarrying, and Oil and Gas Extraction",
  "Other Services (except Public Administration)",
  "Professional, Scientific, and Technical Services",
  "Real Estate and Rental and Leasing",
  "Retail Trade",
  "Transportation and Warehousing",
  "Utilities",
  "Wholesale Trade",
]);

export const VERTICALS_BY_INDUSTRY = Object.freeze({
  "Accommodation and Food Services": Object.freeze([
    "Casino Hotels",
    "Caterers",
    "Drinking Places (Alcoholic Beverages)",
    "Food Service Contractors",
    "Hotels (except Casino Hotels) and Motels",
    "Mobile Food Services",
    "Other Traveler Accommodation",
    "Restaurants and Other Eating Places",
    "Rooming and Boarding Houses, Dormitories, and Workers' Camps",
    "RV (Recreational Vehicle) Parks and Recreational Camps",
  ]),
  "Administrative and Support and Waste Management and Remediation Services": Object.freeze([
    "All Other Support Services",
    "All Other Waste Management Services",
    "Business Service Centers",
    "Carpet and Upholstery Cleaning Services",
    "Collection Agencies",
    "Convention and Trade Show Organizers",
    "Credit Bureaus",
    "Document Preparation Services",
    "Employment Placement Agencies and Executive Search Services",
    "Exterminating and Pest Control Services",
    "Facilities Support Services",
    "Investigation, Guard, and Armored Car Services",
    "Janitorial Services",
    "Landscaping Services",
    "Materials Recovery Facilities",
    "Office Administrative Services",
    "Other Business Support Services",
    "Other Services to Buildings and Dwellings",
    "Other Travel Arrangement and Reservation Services",
    "Packaging and Labeling Services",
    "Professional Employer Organizations",
    "Remediation Services",
    "Security Systems Services",
    "Telephone Call Centers",
    "Temporary Help Services",
    "Tour Operators",
    "Travel Agencies",
    "Waste Collection",
    "Waste Treatment and Disposal",
  ]),
  "Agriculture, Forestry, Fishing and Hunting": Object.freeze([
    "Logging",
    "Support Activities for Animal Production",
    "Support Activities for Crop Production",
    "Support Activities for Forestry",
  ]),
  "Arts, Entertainment, and Recreation": Object.freeze([
    "Agents and Managers for Artists, Athletes, Entertainers, and Other Public Figures",
    "All Other Amusement and Recreation Industries",
    "Amusement and Theme Parks",
    "Amusement Arcades",
    "Bowling Centers",
    "Casinos (except Casino Hotels)",
    "Dance Companies",
    "Fitness and Recreational Sports Centers",
    "Golf Courses and Country Clubs",
    "Historical Sites",
    "Independent Artists, Writers, and Performers",
    "Marinas",
    "Museums",
    "Musical Groups and Artists",
    "Other Gambling Industries",
    "Promoters of Performing Arts, Sports, and Similar Events with Facilities",
    "Promoters of Performing Arts, Sports, and Similar Events without Facilities",
    "Skiing Facilities",
    "Spectator Sports",
    "Theater Companies and Dinner Theaters",
    "Zoos and Botanical Gardens",
  ]),
  "Construction": Object.freeze([
    "All Other Specialty Trade Contractors",
    "Commercial and Institutional Building Construction",
    "Drywall and Insulation Contractors",
    "Electrical Contractors and Other Wiring Installation Contractors",
    "Finish Carpentry Contractors",
    "Flooring Contractors",
    "Framing Contractors",
    "Glass and Glazing Contractors",
    "Highway, Street, and Bridge Construction",
    "Industrial Building Construction",
    "Land Subdivision",
    "Masonry Contractors",
    "Oil and Gas Pipeline and Related Structures Construction",
    "Other Building Equipment Contractors",
    "Other Building Finishing Contractors",
    "Other Foundation, Structure, and Building Exterior Contractors",
    "Other Heavy and Civil Engineering Construction",
    "Painting and Wall Covering Contractors",
    "Plumbing, Heating, and Air-Conditioning Contractors",
    "Poured Concrete Foundation and Structure Contractors",
    "Power and Communication Line and Related Structures Construction",
    "Residential Building Construction",
    "Roofing Contractors",
    "Siding Contractors",
    "Site Preparation Contractors",
    "Structural Steel and Precast Concrete Contractors",
    "Tile and Terrazzo Contractors",
    "Water and Sewer Line and Related Structures Construction",
  ]),
  "Educational Services": Object.freeze([
    "All Other Schools and Instruction",
    "Colleges, Universities, and Professional Schools",
    "Computer Training",
    "Educational Support Services",
    "Elementary and Secondary Schools",
    "Fine Arts Schools",
    "Junior Colleges",
    "Language Schools",
    "Professional and Management Development Training",
    "Sports and Recreation Instruction",
    "Technical and Trade Schools",
  ]),
  "Finance and Insurance": Object.freeze([
    "All Other Financial Investment Activities",
    "Commercial Banking",
    "Commodity Contracts Brokerage",
    "Commodity Contracts Dealing",
    "Credit Card Issuing",
    "Credit Unions",
    "Direct Insurance (except Life, Health, and Medical) Carriers",
    "Direct Life, Health, and Medical Insurance Carriers",
    "Financial Transactions Processing, Reserve, and Clearinghouse Activities",
    "Insurance Agencies and Brokerages",
    "Investment Advice",
    "Investment Banking and Securities Dealing",
    "Miscellaneous Intermediation",
    "Mortgage and Nonmortgage Loan Brokers",
    "Open-End Investment Funds",
    "Other Activities Related to Credit Intermediation",
    "Other Financial Vehicles",
    "Other Insurance Related Activities",
    "Other Nondepository Credit Intermediation",
    "Portfolio Management",
    "Reinsurance Carriers",
    "Sales Financing",
    "Savings Institutions",
    "Securities Brokerage",
  ]),
  "Health Care and Social Assistance": Object.freeze([
    "All Other Ambulatory Health Care Services",
    "Ambulance Services",
    "Child and Youth Services",
    "Child Care Services",
    "Community Food Services",
    "Community Housing Services",
    "Continuing Care Retirement Communities and Assisted Living Facilities for the Elderly",
    "Emergency and Other Relief Services",
    "Family Planning Centers",
    "General Medical and Surgical Hospitals",
    "Home Health Care Services",
    "Medical and Diagnostic Laboratories",
    "Nursing Care Facilities (Skilled Nursing Facilities)",
    "Offices of All Other Health Practitioners",
    "Offices of Chiropractors",
    "Offices of Dentists",
    "Offices of Mental Health Practitioners (except Physicians)",
    "Offices of Optometrists",
    "Offices of Physical, Occupational and Speech Therapists, and Audiologists",
    "Offices of Physicians",
    "Other Individual and Family Services",
    "Other Outpatient Care Centers",
    "Other Residential Care Facilities",
    "Outpatient Mental Health and Substance Abuse Centers",
    "Residential Intellectual and Developmental Disability Facilities",
    "Residential Mental Health and Substance Abuse Facilities",
    "Services for the Elderly and Persons with Disabilities",
    "Specialty (except Psychiatric and Substance Abuse) Hospitals",
    "Vocational Rehabilitation Services",
  ]),
  "Information": Object.freeze([
    "All Other Information Services",
    "Book Publishers",
    "Cable and Other Subscription Programming",
    "Computing Infrastructure Providers, Data Processing, Web Hosting, and Related Services",
    "Directory and Mailing List Publishers",
    "Internet Publishing and Broadcasting and Web Search Portals",
    "Libraries and Archives",
    "Motion Picture and Video Distribution",
    "Motion Picture and Video Exhibition",
    "Motion Picture and Video Production",
    "News Syndicates",
    "Newspaper Publishers",
    "Other Publishers",
    "Other Sound Recording Industries",
    "Other Telecommunications",
    "Periodical Publishers",
    "Postproduction Services and Other Motion Picture and Video Industries",
    "Radio Broadcasting",
    "Record Production and Distribution",
    "Satellite Telecommunications",
    "Software Publishers",
    "Sound Recording Studios",
    "Television Broadcasting",
    "Wired and Wireless Telecommunications Carriers",
  ]),
  "Management of Companies and Enterprises": Object.freeze([
    "Management of Companies and Enterprises",
  ]),
  "Manufacturing": Object.freeze([
    "Adhesive Manufacturing",
    "Aerospace Product and Parts Manufacturing",
    "Agricultural Implement Manufacturing",
    "All Other Chemical Product and Preparation Manufacturing",
    "All Other Electrical Equipment and Component Manufacturing",
    "All Other Fabricated Metal Product Manufacturing",
    "All Other Food Manufacturing",
    "All Other General Purpose Machinery Manufacturing",
    "All Other Miscellaneous Manufacturing",
    "All Other Nonmetallic Mineral Product Manufacturing",
    "All Other Textile Product Mills",
    "All Other Wood Product Manufacturing",
    "Animal Food Manufacturing",
    "Animal Slaughtering and Processing",
    "Apparel Accessories and Other Apparel Manufacturing",
    "Asphalt Paving, Roofing, and Saturated Materials Manufacturing",
    "Audio and Video Equipment Manufacturing",
    "Blind and Shade Manufacturing",
    "Bread and Bakery Product Manufacturing",
    "Breweries",
    "Chocolate and Confectionery Manufacturing",
    "Clay Building Material and Refractories Manufacturing",
    "Coating, Engraving, Heat Treating, and Allied Activities",
    "Coffee and Tea Manufacturing",
    "Commercial and Service Industry Machinery Manufacturing",
    "Computer and Peripheral Equipment Manufacturing",
    "Concrete Pipe, Brick, and Block Manufacturing",
    "Cookie, Cracker, and Pasta Manufacturing",
    "Curtain and Linen Mills",
    "Cut and Sew Apparel Contractors",
    "Cutlery and Handtool Manufacturing",
    "Dairy Product (except Frozen) Manufacturing",
    "Distilleries",
    "Doll, Toy, and Game Manufacturing",
    "Electrical Equipment Manufacturing",
    "Engine, Turbine, and Power Transmission Equipment Manufacturing",
    "Fertilizer and Compost Manufacturing",
    "Footwear Manufacturing",
    "Frozen Food Manufacturing",
    "Fruit and Vegetable Canning, Pickling, and Drying",
    "Glass and Glass Product Manufacturing",
    "Hardware Manufacturing",
    "Household and Institutional Furniture Manufacturing",
    "Ice Cream and Frozen Dessert Manufacturing",
    "Industrial Machinery Manufacturing",
    "Iron and Steel Mills and Ferroalloy Manufacturing",
    "Iron and Steel Pipe and Tube Manufacturing from Purchased Steel",
    "Jewelry and Silverware Manufacturing",
    "Laminated Plastics Plate, Sheet (except Packaging), and Shape Manufacturing",
    "Lighting Fixture Manufacturing",
    "Machine Shops",
    "Manufacturing and Reproducing Magnetic and Optical Media",
    "Material Handling Equipment Manufacturing",
    "Mattress Manufacturing",
    "Medical Equipment and Supplies Manufacturing",
    "Metal Can, Box, and Other Metal Container (Light Gauge) Manufacturing",
    "Metalworking Machinery Manufacturing",
    "Millwork",
    "Mining and Oil and Gas Field Machinery Manufacturing",
    "Motor Vehicle Body and Trailer Manufacturing",
    "Motor Vehicle Gasoline Engine and Engine Parts Manufacturing",
    "Motor Vehicle Steering and Suspension Components (except Spring) Manufacturing",
    "Navigational, Measuring, Electromedical, and Control Instruments Manufacturing",
    "Nonchocolate Confectionery Manufacturing",
    "Nonferrous Metal Foundries",
    "Office Furniture (including Fixtures) Manufacturing",
    "Ornamental and Architectural Metal Products Manufacturing",
    "Other Basic Organic Chemical Manufacturing",
    "Other Concrete Product Manufacturing",
    "Other Converted Paper Product Manufacturing",
    "Other Leather and Allied Product Manufacturing",
    "Other Motor Vehicle Parts Manufacturing",
    "Other Plastics Product Manufacturing",
    "Other Rubber Product Manufacturing",
    "Other Transportation Equipment Manufacturing",
    "Paint and Coating Manufacturing",
    "Paperboard Container Manufacturing",
    "Pharmaceutical and Medicine Manufacturing",
    "Plastics Bottle Manufacturing",
    "Plastics Packaging Materials and Unlaminated Film and Sheet Manufacturing",
    "Plastics Pipe, Pipe Fitting, and Unlaminated Profile Shape Manufacturing",
    "Plate Work and Fabricated Structural Product Manufacturing",
    "Polystyrene Foam Product Manufacturing",
    "Pottery, Ceramics, and Plumbing Fixture Manufacturing",
    "Printing",
    "Radio and Television Broadcasting and Wireless Communications Equipment Manufacturing",
    "Ready-Mix Concrete Manufacturing",
    "Resin and Synthetic Rubber Manufacturing",
    "Sawmills and Wood Preservation",
    "Seasoning and Dressing Manufacturing",
    "Semiconductor and Other Electronic Component Manufacturing",
    "Sign Manufacturing",
    "Snack Food Manufacturing",
    "Soap and Cleaning Compound Manufacturing",
    "Soft Drink and Ice Manufacturing",
    "Sporting and Athletic Goods Manufacturing",
    "Spring and Wire Product Manufacturing",
    "Support Activities for Printing",
    "Textile Bag and Canvas Mills",
    "Toilet Preparation Manufacturing",
    "Tortilla Manufacturing",
    "Turned Product and Screw, Nut, and Bolt Manufacturing",
    "Urethane and Other Foam Product (except Polystyrene) Manufacturing",
    "Veneer, Plywood, and Engineered Wood Product Manufacturing",
    "Ventilation, Heating, Air-Conditioning, and Commercial Refrigeration Equipment Manufacturing",
    "Wineries",
    "Women’s, Girls’, and Infants’ Cut and Sew Apparel Manufacturing",
    "Wood Container and Pallet Manufacturing",
    "Wood Kitchen Cabinet and Countertop Manufacturing",
  ]),
  "Mining, Quarrying, and Oil and Gas Extraction": Object.freeze([
    "Crude Petroleum Extraction",
    "Gold Ore and Silver Ore Mining",
    "Natural Gas Extraction",
    "Sand, Gravel, Clay, and Ceramic and Refractory Minerals Mining and Quarrying",
    "Stone Mining and Quarrying",
    "Support Activities for Mining",
  ]),
  "Other Services (except Public Administration)": Object.freeze([
    "All Other Personal Services",
    "Automotive Body, Paint, Interior, and Glass Repair",
    "Automotive Mechanical and Electrical Repair and Maintenance",
    "Business Associations",
    "Cemeteries and Crematories",
    "Civic and Social Organizations",
    "Coin-Operated Laundries and Drycleaners",
    "Commercial and Industrial Machinery and Equipment (except Automotive and Electronic) Repair and Maintenance",
    "Drycleaning and Laundry Services (except Coin-Operated)",
    "Electronic and Precision Equipment Repair and Maintenance",
    "Footwear and Leather Goods Repair",
    "Funeral Homes and Funeral Services",
    "Grantmaking and Giving Services",
    "Hair, Nail, and Skin Care Services",
    "Home and Garden Equipment and Appliance Repair and Maintenance",
    "Labor Unions and Similar Labor Organizations",
    "Linen and Uniform Supply",
    "Other Automotive Repair and Maintenance",
    "Other Personal and Household Goods Repair and Maintenance",
    "Other Personal Care Services",
    "Other Similar Organizations (except Business, Professional, Labor, and Political Organizations)",
    "Parking Lots and Garages",
    "Pet Care (except Veterinary) Services",
    "Photofinishing",
    "Political Organizations",
    "Professional Organizations",
    "Religious Organizations",
    "Reupholstery and Furniture Repair",
    "Social Advocacy Organizations",
  ]),
  "Professional, Scientific, and Technical Services": Object.freeze([
    "Accounting, Tax Preparation, Bookkeeping, and Payroll Services",
    "Advertising Agencies",
    "Advertising Material Distribution Services",
    "All Other Professional, Scientific, and Technical Services",
    "Architectural Services",
    "Building Inspection Services",
    "Computer Systems Design and Related Services",
    "Direct Mail Advertising",
    "Drafting Services",
    "Engineering Services",
    "Environmental Consulting Services",
    "Geophysical Surveying and Mapping Services",
    "Graphic Design Services",
    "Indoor and Outdoor Display Advertising",
    "Industrial Design Services",
    "Interior Design Services",
    "Landscape Architectural Services",
    "Management Consulting Services",
    "Marketing Research and Public Opinion Polling",
    "Media Buying Agencies",
    "Media Representatives",
    "Offices of Lawyers",
    "Other Legal Services",
    "Other Scientific and Technical Consulting Services",
    "Other Services Related to Advertising",
    "Other Specialized Design Services",
    "Photographic Services",
    "Public Relations Agencies",
    "Research and Development in the Physical, Engineering, and Life Sciences",
    "Research and Development in the Social Sciences and Humanities",
    "Surveying and Mapping (except Geophysical) Services",
    "Testing Laboratories and Services",
    "Translation and Interpretation Services",
    "Veterinary Services",
  ]),
  "Real Estate and Rental and Leasing": Object.freeze([
    "Construction, Transportation, Mining, and Forestry Machinery and Equipment Rental and Leasing",
    "Consumer Electronics and Appliances Rental",
    "General Rental Centers",
    "Lessors of Miniwarehouses and Self-Storage Units",
    "Lessors of Nonfinancial Intangible Assets (except Copyrighted Works)",
    "Lessors of Nonresidential Buildings (except Miniwarehouses)",
    "Lessors of Other Real Estate Property",
    "Lessors of Residential Buildings and Dwellings",
    "Office Machinery and Equipment Rental and Leasing",
    "Offices of Real Estate Agents and Brokers",
    "Offices of Real Estate Appraisers",
    "Other Activities Related to Real Estate",
    "Other Commercial and Industrial Machinery and Equipment Rental and Leasing",
    "Other Consumer Goods Rental",
    "Passenger Car Rental and Leasing",
    "Real Estate Property Managers",
    "Truck, Utility Trailer, and RV (Recreational Vehicle) Rental and Leasing",
  ]),
  "Retail Trade": Object.freeze([
    "All Other Miscellaneous Store Retailers",
    "Art Dealers",
    "Automotive Parts and Accessories Stores",
    "Beer, Wine, and Liquor Stores",
    "Book Stores and News Dealers",
    "Children's and Infants' Clothing Stores",
    "Clothing Accessories Stores",
    "Convenience Stores",
    "Cosmetics, Beauty Supplies, and Perfume Stores",
    "Department Stores",
    "Electronic Shopping and Mail-Order Houses",
    "Electronics and Appliance Stores",
    "Family Clothing Stores",
    "Floor Covering Stores",
    "Florists",
    "Fruit and Vegetable Retailers",
    "Fuel Dealers",
    "Furniture Stores",
    "Gasoline Stations with Convenience Stores",
    "General Merchandise Stores, including Warehouse Clubs and Supercenters",
    "Gift, Novelty, and Souvenir Stores",
    "Hardware Stores",
    "Hobby, Toy, and Game Stores",
    "Home Centers",
    "Jewelry Stores",
    "Luggage and Leather Goods Stores",
    "Manufactured (Mobile) Home Dealers",
    "Meat Markets",
    "Men's Clothing Stores",
    "Motorcycle, Boat, and Other Motor Vehicle Dealers",
    "Musical Instrument and Supplies Stores",
    "New Car Dealers",
    "Nursery, Garden Center, and Farm Supply Stores",
    "Office Supplies and Stationery Stores",
    "Optical Goods Stores",
    "Other Building Material Dealers",
    "Other Clothing Stores",
    "Other Direct Selling Establishments",
    "Other Gasoline Stations",
    "Other Health and Personal Care Stores",
    "Other Home Furnishings Stores",
    "Other Specialty Food Retailers",
    "Other Specialty Food Stores",
    "Outdoor Power Equipment Stores",
    "Paint and Wallpaper Retailers",
    "Pet and Pet Supplies Stores",
    "Pharmacies and Drug Stores",
    "Recreational Vehicle Dealers",
    "Sewing, Needlework, and Piece Goods Stores",
    "Shoe Stores",
    "Sporting Goods Stores",
    "Supermarkets and Other Grocery Retailers (except Convenience Retailers)",
    "Tire Dealers",
    "Used Car Dealers",
    "Used Merchandise Stores",
    "Vending Machine Operators",
    "Women's Clothing Stores",
  ]),
  "Transportation and Warehousing": Object.freeze([
    "Airport Operations",
    "Charter Bus Industry",
    "Couriers and Express Delivery Services",
    "Farm Product Warehousing and Storage",
    "Freight Transportation Arrangement",
    "General Freight Trucking, Local",
    "General Freight Trucking, Long-Distance",
    "General Warehousing and Storage",
    "Interurban and Rural Bus Transportation",
    "Limousine Service",
    "Local Messengers and Local Delivery",
    "Motor Vehicle Towing",
    "Nonscheduled Air Transportation",
    "Other Support Activities for Air Transportation",
    "Other Support Activities for Road Transportation",
    "Other Support Activities for Transportation",
    "Other Transit and Ground Passenger Transportation",
    "Other Warehousing and Storage",
    "Pipeline Transportation of Crude Oil",
    "Pipeline Transportation of Natural Gas",
    "Pipeline Transportation of Refined Petroleum Products",
    "Refrigerated Warehousing and Storage",
    "Scenic and Sightseeing Transportation, Land",
    "Scenic and Sightseeing Transportation, Other",
    "Scenic and Sightseeing Transportation, Water",
    "Scheduled Air Transportation",
    "School and Employee Bus Transportation",
    "Specialized Freight (except Used Goods) Trucking, Local",
    "Specialized Freight (except Used Goods) Trucking, Long-Distance",
    "Support Activities for Rail Transportation",
    "Taxi and Ridesharing Services",
    "Used Household and Office Goods Moving",
  ]),
  "Utilities": Object.freeze([
    "Electric Power Generation",
    "Electric Power Transmission, Control, and Distribution",
    "Natural Gas Distribution",
    "Water Supply and Irrigation Systems",
  ]),
  "Wholesale Trade": Object.freeze([
    "Automobile and Other Motor Vehicle Merchant Wholesalers",
    "Beer and Ale Merchant Wholesalers",
    "Book, Periodical, and Newspaper Merchant Wholesalers",
    "Brick, Stone, and Related Construction Material Merchant Wholesalers",
    "Business to Business Electronic Markets",
    "Coal and Other Mineral and Ore Merchant Wholesalers",
    "Computer and Computer Peripheral Equipment and Software Merchant Wholesalers",
    "Confectionery Merchant Wholesalers",
    "Construction and Mining (except Oil Well) Machinery and Equipment Merchant Wholesalers",
    "Dairy Product (except Dried or Canned) Merchant Wholesalers",
    "Drugs and Druggists' Sundries Merchant Wholesalers",
    "Electrical Apparatus and Equipment, Wiring Supplies, and Related Equipment Merchant Wholesalers",
    "Farm and Garden Machinery and Equipment Merchant Wholesalers",
    "Farm Supplies Merchant Wholesalers",
    "Fish and Seafood Merchant Wholesalers",
    "Flower, Nursery Stock, and Florists' Supplies Merchant Wholesalers",
    "Footwear Merchant Wholesalers",
    "Fresh Fruit and Vegetable Merchant Wholesalers",
    "Furniture Merchant Wholesalers",
    "General Line Grocery Merchant Wholesalers",
    "Grain and Field Bean Merchant Wholesalers",
    "Hardware Merchant Wholesalers",
    "Home Furnishing Merchant Wholesalers",
    "Household Appliances, Electric Housewares, and Consumer Electronics Merchant Wholesalers",
    "Industrial and Personal Service Paper Merchant Wholesalers",
    "Industrial Machinery and Equipment Merchant Wholesalers",
    "Industrial Supplies Merchant Wholesalers",
    "Jewelry, Watch, Precious Stone, and Precious Metal Merchant Wholesalers",
    "Livestock Merchant Wholesalers",
    "Lumber, Plywood, Millwork, and Wood Panel Merchant Wholesalers",
    "Meat and Meat Product Merchant Wholesalers",
    "Medical, Dental, and Hospital Equipment and Supplies Merchant Wholesalers",
    "Men's and Boys' Clothing and Furnishings Merchant Wholesalers",
    "Metal Service Centers and Other Metal Merchant Wholesalers",
    "Motor Vehicle Parts (Used) Merchant Wholesalers",
    "Motor Vehicle Supplies and New Parts Merchant Wholesalers",
    "Office Equipment Merchant Wholesalers",
    "Ophthalmic Goods Merchant Wholesalers",
    "Other Chemical and Allied Products Merchant Wholesalers",
    "Other Commercial Equipment Merchant Wholesalers",
    "Other Construction Material Merchant Wholesalers",
    "Other Electronic Parts and Equipment Merchant Wholesalers",
    "Other Farm Product Raw Material Merchant Wholesalers",
    "Other Grocery and Related Products Merchant Wholesalers",
    "Other Miscellaneous Durable Goods Merchant Wholesalers",
    "Other Miscellaneous Nondurable Goods Merchant Wholesalers",
    "Other Professional Equipment and Supplies Merchant Wholesalers",
    "Packaged Frozen Food Merchant Wholesalers",
    "Paint, Varnish, and Supplies Merchant Wholesalers",
    "Petroleum and Petroleum Products Merchant Wholesalers (except Bulk Stations and Terminals)",
    "Petroleum Bulk Stations and Terminals",
    "Photographic Equipment and Supplies Merchant Wholesalers",
    "Piece Goods, Notions, and Other Dry Goods Merchant Wholesalers",
    "Plastics Materials and Basic Forms and Shapes Merchant Wholesalers",
    "Plumbing and Heating Equipment and Supplies (Hydronics) Merchant Wholesalers",
    "Printing and Writing Paper Merchant Wholesalers",
    "Recyclable Material Merchant Wholesalers",
    "Refrigeration Equipment and Supplies Merchant Wholesalers",
    "Roofing, Siding, and Insulation Material Merchant Wholesalers",
    "Service Establishment Equipment and Supplies Merchant Wholesalers",
    "Sporting and Recreational Goods and Supplies Merchant Wholesalers",
    "Stationery and Office Supplies Merchant Wholesalers",
    "Tire and Tube Merchant Wholesalers",
    "Tobacco Product and Electronic Cigarette Merchant Wholesalers",
    "Toy and Hobby Goods and Supplies Merchant Wholesalers",
    "Transportation Equipment and Supplies (except Motor Vehicle) Merchant Wholesalers",
    "Warm Air Heating and Air-Conditioning Equipment and Supplies Merchant Wholesalers",
    "Wholesale Trade Agents and Brokers",
    "Wine and Distilled Alcoholic Beverage Merchant Wholesalers",
    "Women's, Children's, and Infants' Clothing and Accessories Merchant Wholesalers",
  ]),
});

const INDUSTRY_BY_LC = new Map(INDUSTRIES.map((n) => [n.toLowerCase(), n]));
const VERTICAL_BY_LC = (() => {
  const m = new Map();
  for (const [ind, verts] of Object.entries(VERTICALS_BY_INDUSTRY)) {
    for (const v of verts) m.set(`${ind.toLowerCase()}|${v.toLowerCase()}`, v);
  }
  return m;
})();

/**
 * Return the canonical industry name if `name` matches (case-insensitive), else null.
 * Use this to normalize anything that might enter the pipeline uppercased / wrong-cased.
 */
export function canonicalIndustry(name) {
  if (!name || typeof name !== 'string') return null;
  return INDUSTRY_BY_LC.get(name.trim().toLowerCase()) || null;
}

/**
 * Return the canonical vertical name (case-insensitive match) scoped to the
 * given industry, or null if the vertical isn't a valid child of that industry.
 */
export function canonicalVertical(industry, vertical) {
  if (!industry || !vertical) return null;
  const ind = canonicalIndustry(industry);
  if (!ind) return null;
  return VERTICAL_BY_LC.get(`${ind.toLowerCase()}|${String(vertical).trim().toLowerCase()}`) || null;
}

/**
 * Filter an array of verticals down to those that are valid children of
 * `industry`. De-duplicates and returns canonical casing. Safe for any input.
 */
export function filterVerticalsForIndustry(industry, verticals) {
  if (!Array.isArray(verticals)) return [];
  const seen = new Set();
  const out = [];
  for (const v of verticals) {
    const canon = canonicalVertical(industry, v);
    if (canon && !seen.has(canon)) {
      seen.add(canon);
      out.push(canon);
    }
  }
  return out;
}
